### ISSUE TITLE
Undesired string replacement upon inserting graph vertices

### ISSUE THREAD

**Issue by vhilliard** [Azure-Samples/azure-cosmos-db-graph-dotnet-getting-started#4]
Inserting a graph Vertex that contains "g." in a property, will replace that part of the property with "graph.g()." This showed up in the file name property that I am using for vertices that represent a file.

It's possible that it could be isolated to the Cosmos DB Emulator, though.

**Comment by olivertowers** [comment]
This should be resolved with the latest [Microsoft.Azure.Graphs](https://www.nuget.org/packages/Microsoft.Azure.Graphs/0.3.0-preview) nuget package. Can you try this out and verify that it resolves the issue?

**Comment by vhilliard** [comment]
All good, can confirm the issue is resolved. (Though I did have to reconfigure for the 0.3.0-preview version of the package as MSIL was not available using net461)
